import { getGcvPalette, parseGcvTheme } from "@/lib/gcv-design";
import { parseResumeContent, resumeContentToText } from "@/lib/resume-content";

export function buildGcvSvg(input: { title: string; contentJson: unknown; themeJson: unknown }) {
  const content = parseResumeContent(input.contentJson);
  const theme = parseGcvTheme(input.themeJson);
  const palette = getGcvPalette(theme);
  const lines = resumeContentToText(content).split("\n").filter(Boolean).slice(0, 34);
  const width = 1240;
  const height = theme.paper === "A4" ? 1754 : 1604;
  const title = content.header.fullName || input.title;
  const subtitle = content.header.title || "Graphical CV";
  const body = lines.map((line, index) => {
    const y = 300 + index * 34;
    const size = line === "Experience" || line === "Education" || line === "Skills" || line === "Projects" ? 24 : 20;
    const weight = size === 24 ? 700 : 400;
    return `<text x="96" y="${y}" font-size="${size}" font-weight="${weight}" fill="${escapeXml(palette.text)}">${escapeXml(line.slice(0, 105))}</text>`;
  }).join("");

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
  <rect width="100%" height="100%" fill="#ffffff"/>
  <rect x="0" y="0" width="${width}" height="26" fill="${escapeXml(palette.accent)}"/>
  <rect x="72" y="88" width="1096" height="160" rx="18" fill="${escapeXml(palette.muted)}"/>
  <text x="96" y="152" font-family="Inter, Arial, sans-serif" font-size="56" font-weight="800" fill="${escapeXml(palette.text)}">${escapeXml(title)}</text>
  <text x="98" y="204" font-family="Inter, Arial, sans-serif" font-size="28" font-weight="600" fill="${escapeXml(palette.accent)}">${escapeXml(subtitle)}</text>
  <text x="96" y="252" font-family="Inter, Arial, sans-serif" font-size="18" fill="#525252">${escapeXml([content.header.email, content.header.phone, content.header.location].filter(Boolean).join(" | "))}</text>
  ${body}
  <text x="96" y="${height - 80}" font-family="Inter, Arial, sans-serif" font-size="16" fill="#737373">Generated by Career Studio Graphical CV</text>
</svg>`;
}

export function buildGcvPlainHtml(input: { title: string; contentJson: unknown; themeJson: unknown }) {
  const content = parseResumeContent(input.contentJson);
  const theme = parseGcvTheme(input.themeJson);
  const palette = getGcvPalette(theme);
  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(input.title)}</title>
  <style>
    @page { size: ${theme.paper}; margin: 12mm; }
    body { font-family: Inter, Arial, sans-serif; color: ${palette.text}; margin: 0; background: #f5f5f5; }
    main { width: 210mm; min-height: 297mm; margin: 0 auto; background: white; padding: 24mm; box-sizing: border-box; border-top: 8px solid ${palette.accent}; }
    h1 { font-size: 34px; margin: 0; }
    h2 { color: ${palette.accent}; font-size: 18px; margin: 6px 0 18px; }
    pre { white-space: pre-wrap; font: inherit; line-height: 1.55; }
  </style>
</head>
<body>
  <main>
    <h1>${escapeHtml(content.header.fullName || input.title)}</h1>
    <h2>${escapeHtml(content.header.title || "Graphical CV")}</h2>
    <pre>${escapeHtml(resumeContentToText(content))}</pre>
  </main>
</body>
</html>`;
}

function escapeXml(value: string) {
  return value.replace(/[<>&'"]/g, (char) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", "'": "&apos;", "\"": "&quot;" }[char] ?? char));
}

function escapeHtml(value: string) {
  return value.replace(/[<>&'"]/g, (char) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", "'": "&#39;", "\"": "&quot;" }[char] ?? char));
}
