export const slUniversities = [
  "University of Colombo",
  "University of Peradeniya",
  "University of Moratuwa",
  "University of Kelaniya",
  "University of Sri Jayewardenepura",
  "University of Ruhuna",
  "University of Jaffna",
  "University of Rajarata",
  "Wayamba University of Sri Lanka",
  "Sabaragamuwa University of Sri Lanka",
  "South Eastern University of Sri Lanka",
  "Uva Wellassa University",
  "University of the Visual and Performing Arts",
  "General Sir John Kotelawala Defence University (KDU)",
  "Sri Lanka Institute of Information Technology (SLIIT)",
  "Informatics Institute of Technology (IIT)",
  "National Institute of Business Management (NIBM)",
  "National School of Business Management (NSBM)",
  "APIIT Sri Lanka",
  "Horizon Campus",
  "CINEC Campus",
  "ICBT Campus",
  "Aquinas College of Higher Studies"
];

export const slCompanies = [
  "WSO2",
  "Sysco LABS",
  "IFS",
  "Creative Software",
  "Dialog Axiata",
  "Mobitel",
  "MAS Holdings",
  "Brandix",
  "John Keells Holdings (JKH)",
  "Virtusa",
  "Pearson Lanka",
  "MillenniumIT ESP",
  "London Stock Exchange Group (LSEG) Sri Lanka",
  "99x",
  "Mitra Innovation",
  "Surge Global",
  "Cakewalk",
  "Commercial Bank of Ceylon",
  "Hatton National Bank (HNB)",
  "Sampath Bank",
  "Aitken Spence",
  "Hemas Holdings",
  "Softlogic Holdings",
  "Hayleys PLC",
  "Lanka ORIX Leasing Company (LOLC)"
];

export const slDistricts = [
  "Ampara",
  "Anuradhapura",
  "Badulla",
  "Batticaloa",
  "Colombo",
  "Galle",
  "Gampaha",
  "Hambantota",
  "Jaffna",
  "Kalutara",
  "Kandy",
  "Kegalle",
  "Kilinochchi",
  "Kurunegala",
  "Mannar",
  "Matale",
  "Matara",
  "Moneragala",
  "Mullaitivu",
  "Nuwara Eliya",
  "Polonnaruwa",
  "Puttalam",
  "Ratnapura",
  "Trincomalee",
  "Vavuniya"
];
