export const slUniversities = [
  "University of Colombo",
  "University of Peradeniya",
  "University of Moratuwa",
  "University of Kelaniya",
  "University of Sri Jayewardenepura",
  "University of Ruhuna",
  "University of Jaffna",
  "University of Rajarata",
  "Wayamba University of Sri Lanka",
  "Sabaragamuwa University of Sri Lanka",
  "South Eastern University of Sri Lanka",
  "Uva Wellassa University",
  "University of the Visual and Performing Arts",
  "General Sir John Kotelawala Defence University (KDU)",
  "Sri Lanka Institute of Information Technology (SLIIT)",
  "Informatics Institute of Technology (IIT)",
  "National Institute of Business Management (NIBM)",
  "National School of Business Management (NSBM)",
  "APIIT Sri Lanka",
  "Horizon Campus",
  "CINEC Campus",
  "ICBT Campus",
  "Aquinas College of Higher Studies"
];

export const slCompanies = [
  "WSO2",
  "Sysco LABS",
  "IFS",
  "Creative Software",
  "Dialog Axiata",
  "Mobitel",
  "MAS Holdings",
  "Brandix",
  "John Keells Holdings (JKH)",
  "Virtusa",
  "Pearson Lanka",
  "MillenniumIT ESP",
  "London Stock Exchange Group (LSEG) Sri Lanka",
  "99x",
  "Mitra Innovation",
  "Surge Global",
  "Cakewalk",
  "Commercial Bank of Ceylon",
  "Hatton National Bank (HNB)",
  "Sampath Bank",
  "Aitken Spence",
  "Hemas Holdings",
  "Softlogic Holdings",
  "Hayleys PLC",
  "Lanka ORIX Leasing Company (LOLC)",
  "NDB Bank",
  "DFCC Bank",
  "Bank of Ceylon",
  "People's Bank",
  "Cargills Bank",
  "CIC Holdings",
  "Hirdaramani Group",
  "Aitken Spence Hotels",
  "Jetwing Hotels",
  "Cinnamon Hotels",
  "Dilmah Ceylon Tea",
  "Maliban Biscuit Manufactories",
  "Ceylon Biscuits Limited",
  "Unilever Sri Lanka",
  "Nestle Lanka",
  "HCLTech Sri Lanka",
  "Wiley Global Technology",
  "IFS R&D International",
  "WSO2 LLC",
  "Asiri Health",
  "Durdans Hospital",
  "Nawaloka Hospitals",
  "SriLankan Airlines",
  "Expolanka Holdings",
  "PickMe",
  "Daraz Sri Lanka",
  "CodeGen International",
  "Cambio Software Engineering",
  "Calcey Technologies",
  "Zone24x7",
  "Intervest Software Technologies",
  "WSO2 Telco",
  "Dialog Finance",
  "Hutch Sri Lanka",
  "SLT-Mobitel",
  "LAUGFS Holdings",
  "Tokyo Cement",
  "ACL Cables",
  "Sierra Construction",
  "Access Engineering"
];

export const slDistricts = [
  "Ampara",
  "Anuradhapura",
  "Badulla",
  "Batticaloa",
  "Colombo",
  "Galle",
  "Gampaha",
  "Hambantota",
  "Jaffna",
  "Kalutara",
  "Kandy",
  "Kegalle",
  "Kilinochchi",
  "Kurunegala",
  "Mannar",
  "Matale",
  "Matara",
  "Moneragala",
  "Mullaitivu",
  "Nuwara Eliya",
  "Polonnaruwa",
  "Puttalam",
  "Ratnapura",
  "Trincomalee",
  "Vavuniya"
];

export const slCertifications = [
  "CA Sri Lanka",
  "CMA Sri Lanka",
  "AAT Sri Lanka",
  "SLIM",
  "CIPM Sri Lanka",
  "CIMA",
  "ACCA",
  "BCS",
  "AWS Certified Cloud Practitioner",
  "Google Project Management Certificate"
];

export const slEducationTypes = [
  "GCE O/L",
  "GCE A/L - Physical Science",
  "GCE A/L - Biological Science",
  "GCE A/L - Commerce",
  "GCE A/L - Arts",
  "University Degree",
  "Diploma",
  "Professional Qualification"
];

export const slAdvancedLevelStreams = [
  "Physical Science",
  "Biological Science",
  "Commerce",
  "Arts",
  "Technology",
  "Common General"
];
